config/routes.rb
Rails.application.routes.draw do

  # User Devise Routes
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}
  root 'user_dashboards#index'

  scope '/admin' do
    get 'dashboard', to: 'admin/dashboards#index', as: 'admin_dashboard'
    get 'invite-candidate', to: 'admin/users#invite_candidate', as: 'invite_candidate'
    post 'send_invitation_to_candidate', to: 'admin/users#send_invitation_to_candidate', as: 'send_invitation_to_candidate'
    get 'online-candidates', to: 'admin/users#online_candidates',as: 'online_candidates'
    get 'reports', to: 'admin/reports#candidate_reports', as: 'candidate_report'
    get 'candidates', to:  'admin/users#candidates', as: 'candidates'
    get 'questions', to: 'admin/questions#index', as: 'questions'
    post 'check-user', to: 'admin/users#check_user', as: 'check_user'
  end
  get 'dashboard', to: 'user_dashboards#dashboard', as: 'user_dashboard'
  get 'start-test', to: 'user_dashboards#user_set', as: 'user_set'
  post '/update-answer', to: 'user_dashboards#update_answer'
  post '/submit-answer', to: 'user_dashboards#submit_answer'
  post 'timeis-up', to: 'user_dashboards#timeis_up',as:'timeis_up'
  get '/ThankYou', to: 'user_dashboards#thank_you',as:'thank_you'
  get '/404_error', to: 'static_pages#crash'

end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < BaseAdminController

  def index
    
  end

end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<!--<div style="margin-top: 50px">-->
  <!--Welcome to dashboard-->
  <!--<%= link_to 'Sign Out', destroy_user_session_path ,method: 'delete' %>-->
  <!--<%= link_to 'Invite Candidate', invite_candidate_path  %>-->
  <!--<%= link_to 'Online Candidates', online_candidates_path  %>-->
  <!--<%= link_to 'Reports', online_candidates_path  %>-->
<!--</div>-->

<section class="dashboard activate">
  <h2>Welcome Dashboard</h2>
  <div class="col-md-6 cuehunt-description">
    <label class="welcome-note">Welcome</label>
    <p>CueHunt is a portal which  simplifies and optimizes your hiring process.</p>
    <br/>
    <p>It overcomes the challenge of selecting the best candidate. Its seemless technical tests process helps the interviewer to understand the candidates skills and knowledge.</p>
    <br/>
    <p>Truely web based application which is more effecient than email and spreadsheets, giving a relief to recuritment team for selection process.</p>
  </div>

  <div class="col-md-5 report-graph">
    <div id="jqChart" style="width: 600px; height: 320px;"></div>
  </div>

</section>