config/routes.rb
Rails.application.routes.draw do

  # User Devise Routes
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}
  root 'user_dashboards#index'

  scope '/admin' do
    get 'dashboard', to: 'admin/dashboards#index', as: 'admin_dashboard'
    get 'invite-candidate', to: 'admin/users#invite_candidate', as: 'invite_candidate'
    post 'send_invitation_to_candidate', to: 'admin/users#send_invitation_to_candidate', as: 'send_invitation_to_candidate'
    get 'online-candidates', to: 'admin/users#online_candidates',as: 'online_candidates'
    get 'reports', to: 'admin/reports#candidate_reports', as: 'candidate_report'
    get 'candidates', to:  'admin/users#candidates', as: 'candidates'
    get 'questions', to: 'admin/questions#index', as: 'questions'
    post 'check-user', to: 'admin/users#check_user', as: 'check_user'
  end
  get 'dashboard', to: 'user_dashboards#dashboard', as: 'user_dashboard'
  get 'start-test', to: 'user_dashboards#user_set', as: 'user_set'
  post '/update-answer', to: 'user_dashboards#update_answer'
  post '/submit-answer', to: 'user_dashboards#submit_answer'
  post 'timeis-up', to: 'user_dashboards#timeis_up',as:'timeis_up'
  get '/ThankYou', to: 'user_dashboards#thank_you',as:'thank_you'
  get '/404_error', to: 'static_pages#crash'

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :role
  has_many :user_sets

  # Send invitation to candidate to join test
  def self.send_invitation(params, invitee)
    role_id = Role.select('id').where(role_type: 'candidate').first.id rescue nil
    user = new(email: params['email'].first, full_name: params['full_name'].first, phone_no: params['phone_no'].first, password: 'cuehunt2016', password_confirmation: 'cuehunt2016',status: INVITATION_ACCEPTED, role_id: role_id)
    if user.save
      user_set = UserSet.create_user_set(params[:technology_id] ,user.id, invitee.id)
      if user_set.present?
        question_ids = Question.order("RANDOM()").where(technology_id: params[:technology_id]).limit(10).collect(&:id)
        QuestionSet.create_set(question_ids, user_set.id)
      end
    end
  end

  scope :of_type, -> (type) { where(role_id: Role.find_by_role_type(type))}
  # User role
  def is_admin?
    return false if role.blank?
    role.role_type == 'admin'? true : false
  end

  # Current set
  def current_set
    user_sets.last
  end

  # Submit all answers
  def submit_answers
    current_set.update_attributes(status: SET_FINISHED, score: score, end_time: Time.now)
    update_attributes(status: NO_ACCESS)
    AdminNotifier.send_admin_report(current_set).deliver
  end

  # User last test score
  def score
    current_set.question_sets.select('id').where(is_correct: true).count
  end

  # Get list of online candidates
  def self.online_users
    where("last_seen_at >= ?", Time.now - 5.minutes)
  end

  # Resend invitation
  def self.resend_invitation_to_user(user, invitee, params)
    user_set = UserSet.create_user_set(params[:technology_id] ,user.id, invitee.id)
    if user_set.present?
      question_ids = Question.order("RANDOM()").where(technology_id: params[:technology_id]).limit(10).collect(&:id)
      QuestionSet.create_set(question_ids, user_set.id)
    end
    user.update_attributes(status: INVITED)
    AdminNotifier.resend_invitation_email(user).deliver
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < BaseAdminController

  # Send invitation to user
  def send_invitation_to_candidate
    if params[:user_type] == 'new'
      User.send_invitation(params, current_user)
    else
      user = User.where(email: params[:email]).last
      User.resend_invitation_to_user(user, current_user, params) if user.present?
    end
    redirect_to :back
  end

  def online_candidates
    @online_candidate = User.online_users
  end

  def candidates
    @candidates = User.of_type("candidate")
    @online_user_ids = User.online_users.collect(&:email)
  end

  def check_user
    if params[:user_type] == 'exist'
      @emails = User.of_type("candidate").collect(&:email)
    end
    render partial: 'admin/reports/email_field'
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

  layout 'admin/login'

  def show
    super do |resource|
      sign_in(resource)
    end
  end

  def after_confirmation_path_for(resource_name, resource)
    user_dashboard_path
  end


end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  layout 'admin/login'


  # POST /resource/password
  def create
    user = User.where(email: params[:user][:email]).last
    if user.present? && !user.is_admin?
      return redirect_to thank_you_path
    end
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    yield resource if block_given?

    if successfully_sent?(resource)
      respond_with({}, location: after_sending_reset_password_instructions_path_for(resource_name))
    else
      respond_with(resource)
    end
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    new_session_path(resource_name,password_reset_link: 'sent') if is_navigational_format?
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  def new
    return redirect_to user_session_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  layout 'admin/login'

  def after_sign_in_path_for(resource)
    admin_dashboard_path
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/candidates.html.erb
<section class="candidate activate">
  <h2>Candidate Activity</h2>
  <div class="candidate-view">
    <!-- Left Panel -->
    <div class="col-md-8 candidate-list left-panel">
      <h2>Candidate List</h2>
      <div class="tabulate-view">
        <table class="table table-striped scroll"  width="813">
          <thead>
          <tr>
            <td width="200px">Name</td>
            <td width="280px">Email</td>
            <td width="180px">Contact</td>
            <td width="200px">Technology</td>
          </tr>
          </thead>
          <tbody>
          <% @candidates.each do |candidate| %>
            <tr>
              <td width="200px">
                <% if @online_user_ids.include?(candidate.id) %>
                  <span class = 'online-users'></span>
                <% end %>
                <%= candidate.full_name %>
              </td>
              <td width="300px"> <%= candidate.email %> </td>
              <td width="200px"> <%= candidate.phone_no %> </td>
              <td width="200px"> <%= UserSet.where(user_id: candidate.id).first.try(:technology).try(:name) %> </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Right Panel -->
    <div class="col-md-4 right-panel">
      <div class="new-candidate-registration">
        <h2>Sending Invite</h2>
        <%= form_tag send_invitation_to_candidate_path, class: 'form-signin' do %>
              <%= radio_button_tag 'user_type','new', true, {class: 'candidate-selection', style: 'margin-left: 1px !important',onclick: "check_user('new')"} %>
              New Candidate
              <%= radio_button_tag 'user_type', 'exist', false, {class: 'candidate-selection', style: 'margin-left: 1px',onclick: "check_user('exist')"} %>
              Existing Candidate<br/><br/>
              <div id="email_field">
                <%= render 'admin/reports/email_field' %>
              </div>
              <%= text_field 'full_name',nil, autofocus: true, class: "form-control", placeholder: "Name", required: true %>
              <%= text_field 'phone_no',nil, autofocus: true, class: "form-control", placeholder: "Contact Number", required: true %>
              <%= select_tag 'technology_id',options_for_select(Technology.all.map {|t| [t.name, t.id]}), class: "form-control" %>
            <%= submit_tag 'Invite', class: "btn btn-lg send-invite btn-primary", style: 'margin-left: 90px !important' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

<script>
  function check_user(type){
      $.ajax({
          url: '/admin/check-user',
          method: 'POST',
          beforeSend: function (xhr) {
              xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
          },
          data: {user_type: type},
          success :function(data){
            $("#email_field").html(data)
          }
      })
  }
</script>

app/views/admin/users/invite_candidate.html.erb
<%= form_tag send_invitation_to_candidate_path, class: 'form-signin' do %>
    <%= email_field 'email',nil, autofocus: true, class: "form-control", placeholder: "Email", required: true %><br/>
    <%= text_field 'full_name',nil, autofocus: true, class: "form-control", placeholder: "Name", required: true %><br/>
    <%= text_field 'phone_no',nil, autofocus: true, class: "form-control", placeholder: "Contact Number", required: true %><br/>
    <%= select_tag 'technology_id',options_for_select(Technology.all.map {|t| [t.name, t.id]}), class: "form-control" %><br/>
    <%= submit_tag 'Invite', class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/admin/users/online_candidates.html.erb
<% @online_candidate.each do |candidate | %>
    <%= candidate.email %><br/>
<% end %>