config/routes.rb
Rails.application.routes.draw do

  # User Devise Routes
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords', confirmations: 'users/confirmations'}
  root 'user_dashboards#index'

  scope '/admin' do
    get 'dashboard', to: 'admin/dashboards#index', as: 'admin_dashboard'
    get 'invite-candidate', to: 'admin/users#invite_candidate', as: 'invite_candidate'
    post 'send_invitation_to_candidate', to: 'admin/users#send_invitation_to_candidate', as: 'send_invitation_to_candidate'
    get 'online-candidates', to: 'admin/users#online_candidates',as: 'online_candidates'
    get 'reports', to: 'admin/reports#candidate_reports', as: 'candidate_report'
    get 'candidates', to:  'admin/users#candidates', as: 'candidates'
    get 'questions', to: 'admin/questions#index', as: 'questions'
    post 'check-user', to: 'admin/users#check_user', as: 'check_user'
  end
  get 'dashboard', to: 'user_dashboards#dashboard', as: 'user_dashboard'
  get 'start-test', to: 'user_dashboards#user_set', as: 'user_set'
  post '/update-answer', to: 'user_dashboards#update_answer'
  post '/submit-answer', to: 'user_dashboards#submit_answer'
  post 'timeis-up', to: 'user_dashboards#timeis_up',as:'timeis_up'
  get '/ThankYou', to: 'user_dashboards#thank_you',as:'thank_you'
  get '/404_error', to: 'static_pages#crash'

end

app/views/admin_notifier/exception_report.html.erb
<p>An exception was thrown. Details are below.</p>
<h2>Exception</h2>
<%= h @exception %>
<br />
<h2>Backtrace</h2>
<pre>
<% @backtrace.each do |value| %>
<%= value %>
<% end %>
</pre>
<br />
<h2>Session Variables</h2>
<% if @session_variables %>
  <% @session_variables.each do |key, value| %>
    <strong><%= key %></strong> => <%= value %><br />
  <% end %>
<% end %>
<br />
<h2>Params</h2>
<% if @prams %>
  <% @prams.each do |key, value| %>
    <strong><%= key %></strong> => <%= value %><br />
  <% end %>
<% end %>
<br />
<h2>Environment</h2>
<% if @env %>
  <% @env.each do |key, value| %>
    <strong><%= key %></strong> => <%= value %><br />
  <% end %>
<% end %>

app/views/admin_notifier/resend_invitation_email.html.erb
Hello <%= @full_name %>
<br/><br/>
Welcome to Cuehunt.
<br/><br/>
You are requested to please click on this <%= link_to 'Click Here', user_dashboard_url %> to start your test.
<br/><br/>
All the best.
<br/><br/>
HR - Team
CueHunt

app/views/admin_notifier/send_admin_report.html.erb
User: <%= @current_set.user.email %><br/>
Score: <%= @current_set.score %><br/>
Start Time: <%= @current_set.start_time.strftime("%I:%M%p") %><br/>
End Time: <%= @current_set.end_time.strftime("%I:%M%p") %>